using System.Collections.Generic;
using ProductScanner.Core.Scanning.FileLoading;
using ProductScanner.Core.Scanning.Products.Vendor;
using ProductScanner.Core.Scanning.Storage;

namespace Surya
{
    public class SuryaFileLoader : ProductFileLoader<SuryaVendor>
    {
        private static readonly List<FileProperty> Properties = new List<FileProperty>
        {
            new FileProperty("Introduced", ScanField.Bullet1),
            new FileProperty("Sku", ScanField.ManufacturerPartNumber),
            new FileProperty("Design-Name", ScanField.Ignore),
            new FileProperty("DesignName", ScanField.Pattern),
            new FileProperty("Master ID", ScanField.ManufacturerPartNumber),
            new FileProperty("Parent ID", ScanField.PatternCorrelator),
            new FileProperty("UPC", ScanField.UPC),
            new FileProperty("Product Name", ScanField.ProductName),
            new FileProperty("Collection", ScanField.Collection),
            new FileProperty("Designer", ScanField.Designer),
            new FileProperty("Brand", ScanField.Brand),
            new FileProperty("Brand Copy", ScanField.Brand),
            new FileProperty("Romance Copy", ScanField.Brand),
            new FileProperty("MSRP", ScanField.Brand),
            new FileProperty("EMAP", ScanField.Brand),
            new FileProperty("Ecom Cost", ScanField.Cost),
            new FileProperty("Number of Items Included", ScanField.Brand),
            new FileProperty("Pieces Included", ScanField.Brand),
            new FileProperty("Top Seller", ScanField.Brand),
            new FileProperty("Commercial Use", ScanField.Brand),
            new FileProperty("Product Category", ScanField.Brand),
            new FileProperty("Product Type", ScanField.Brand),
            new FileProperty("Keywords", ScanField.Brand),
            new FileProperty("Related Items", ScanField.Brand),
            new FileProperty("Country of Origin", ScanField.Brand),
            new FileProperty("Construction Group", ScanField.Brand),
            new FileProperty("Construction", ScanField.Brand),
            new FileProperty("Knot Type", ScanField.Brand),
            new FileProperty("Details", ScanField.Brand),
            new FileProperty("Generic Materials", ScanField.Brand),
            new FileProperty("Specific Materials", ScanField.Brand),
            new FileProperty("Backing", ScanField.Brand),
            new FileProperty("NRF Color Code", ScanField.Brand),
            new FileProperty("Navigational Color", ScanField.Brand),
            new FileProperty("Family Color", ScanField.Brand),
            new FileProperty("Colors", ScanField.Brand),
            new FileProperty("Pantone #", ScanField.Brand),
            new FileProperty("Style", ScanField.Brand),
            new FileProperty("Pattern", ScanField.Brand),
            new FileProperty("Shape", ScanField.Brand),
            new FileProperty("Theme", ScanField.Brand),
            new FileProperty("Holiday", ScanField.Brand),
            new FileProperty("Gender", ScanField.Brand),
            new FileProperty("Lifestage", ScanField.Brand),
            new FileProperty("Reversible", ScanField.Brand),
            new FileProperty("Distressed", ScanField.Brand),
            new FileProperty("Border Color", ScanField.Brand),
            new FileProperty("Border Material", ScanField.Brand),
            new FileProperty("Border Material Details", ScanField.Brand),
            new FileProperty("Fringe", ScanField.Brand),
            new FileProperty("Outdoor Safe?", ScanField.Brand),
            new FileProperty("Rug Pad Needed?", ScanField.Brand),
            new FileProperty("Product Care", ScanField.Brand),
            new FileProperty("Product Warranty", ScanField.Brand),
            new FileProperty("Assembly Required?", ScanField.Brand),
            new FileProperty("Product Weight - Lbs", ScanField.Brand),
            new FileProperty("Product Weight - G", ScanField.Brand),
            new FileProperty("Diameter", ScanField.Brand),
            new FileProperty("Master Size", ScanField.Brand),
            new FileProperty("NRF Size Code", ScanField.Brand),
            new FileProperty("Size - Ft", ScanField.Brand),
            new FileProperty("Size - In", ScanField.Brand),
            new FileProperty("Size - Cm", ScanField.Brand),
            new FileProperty("Width - Ft", ScanField.Brand),
            new FileProperty("Length - Ft", ScanField.Brand),
            new FileProperty("Width - In", ScanField.Brand),
            new FileProperty("Length - In", ScanField.Brand),
            new FileProperty("Width - Cm", ScanField.Brand),
            new FileProperty("Length - Cm", ScanField.Brand),
            new FileProperty("Pile", ScanField.Brand),
            new FileProperty("Pile Height - In", ScanField.Brand),
            new FileProperty("Pile Height - Cm", ScanField.Brand),
            new FileProperty("Custom Size Available?", ScanField.Brand),
            new FileProperty("Swatch Available", ScanField.Brand),
            new FileProperty("Main Image", ScanField.Brand),
            new FileProperty("Additional Image 1", ScanField.Brand),
            new FileProperty("Additional Image 2", ScanField.Brand),
            new FileProperty("Additional Image 3", ScanField.Brand),
            new FileProperty("Additional Image 4", ScanField.Brand),
            new FileProperty("Additional Products Shown in Images", ScanField.Brand),
            new FileProperty("Video Link", ScanField.Brand),
            new FileProperty("Lead Time", ScanField.Brand),
            new FileProperty("Ship Method", ScanField.Brand),
            new FileProperty("NMFC Code", ScanField.Brand),
            new FileProperty("HTS Code", ScanField.Brand),
            new FileProperty("Freight Class", ScanField.Brand),
            new FileProperty("Carton Weight - Lbs", ScanField.Brand),
            new FileProperty("Carton Weight - G", ScanField.Brand),
            new FileProperty("Carton Weight - G", ScanField.Brand),
        };

        public SuryaFileLoader(IStorageProvider<SuryaVendor> storageProvider)
            : base(storageProvider, ScanField.ManufacturerPartNumber, Properties) { }
    }
}