using System.Collections.Generic;
using System.IO;
using System.Linq;
using ProductScanner.Core.Scanning.FileLoading;
using ProductScanner.Core.Scanning.Products.Vendor;
using ProductScanner.Core.Scanning.Storage;

namespace SuryaHomeware
{
    public class SuryaPoufFileLoader
    {
        private readonly List<FileProperty> _properties = new List<FileProperty>
        {
            new FileProperty("Introduced", ScanField.Bullet1),
            new FileProperty("Sku", ScanField.ManufacturerPartNumber),
            new FileProperty("Design-Name", ScanField.PatternNumber),
            new FileProperty("DesignName", ScanField.Pattern),
            new FileProperty("Parent ID", ScanField.PatternCorrelator),
            new FileProperty("Master ID", ScanField.Ignore),
            new FileProperty("UPC", ScanField.UPC),
            new FileProperty("Product Name", ScanField.ProductName),
            new FileProperty("Collection", ScanField.Collection),
            new FileProperty("Designer", ScanField.Designer),
            new FileProperty("Brand", ScanField.Ignore),
            new FileProperty("Brand Copy", ScanField.Ignore),
            new FileProperty("Romance Copy", ScanField.Ignore),
            new FileProperty("MSRP", ScanField.Ignore),
            new FileProperty("EMAP", ScanField.Ignore),
            new FileProperty("Ecom Cost", ScanField.Cost),
            new FileProperty("Number of Items Included", ScanField.Ignore),
            new FileProperty("Pieces Included", ScanField.Ignore),
            new FileProperty("Top Seller", ScanField.Ignore),
            new FileProperty("Commercial Use", ScanField.Ignore),
            new FileProperty("Product Category", ScanField.Category),
            new FileProperty("Product Type", ScanField.Ignore),
            new FileProperty("Keywords", ScanField.Ignore),
            new FileProperty("Related Items", ScanField.Ignore),
            new FileProperty("Country of Origin", ScanField.Ignore),
            new FileProperty("Construction Group", ScanField.Ignore),
            new FileProperty("Construction", ScanField.Ignore),
            new FileProperty("Generic Materials", ScanField.Ignore),
            new FileProperty("Specific Materials", ScanField.Ignore),
            new FileProperty("Fill Material", ScanField.Ignore),
            new FileProperty("Navigational Color", ScanField.Ignore),
            new FileProperty("Colors", ScanField.Ignore),
            new FileProperty("Pantone #", ScanField.Ignore),
            new FileProperty("Style", ScanField.Ignore),
            new FileProperty("Pattern", ScanField.Ignore),
            new FileProperty("Print", ScanField.Ignore),
            new FileProperty("Shape", ScanField.Ignore),
            new FileProperty("Coils or Springs", ScanField.Ignore),
            new FileProperty("Number of Coils", ScanField.Ignore),
            new FileProperty("Coil Gauge", ScanField.Ignore),
            new FileProperty("Eight-Way Hand Tied", ScanField.Ignore),
            new FileProperty("Tufted Cushion", ScanField.Ignore),
            new FileProperty("Slipcovered", ScanField.Ignore),
            new FileProperty("Legs Included", ScanField.Ignore),
            new FileProperty("Removable Legs", ScanField.Ignore),
            new FileProperty("Leg Material", ScanField.Ignore),
            new FileProperty("Leg Finish", ScanField.Ignore),
            new FileProperty("Glider", ScanField.Ignore),
            new FileProperty("Nailhead Trim", ScanField.Ignore),
            new FileProperty("Tray Top", ScanField.Ignore),
            new FileProperty("Number of Trays", ScanField.Ignore),
            new FileProperty("Storage Available", ScanField.Ignore),
            new FileProperty("Storage Shelves", ScanField.Ignore),
            new FileProperty("Number of Drawers", ScanField.Ignore),
            new FileProperty("Hinged Lid", ScanField.Ignore),
            new FileProperty("Lift-Off Lid", ScanField.Ignore),
            new FileProperty("Pull Out Bed", ScanField.Ignore),
            new FileProperty("Hardware Finish", ScanField.Ignore),
            new FileProperty("Distressed", ScanField.Ignore),
            new FileProperty("Frame Material", ScanField.Ignore),
            new FileProperty("Frame Material Details", ScanField.Ignore),
            new FileProperty("Hardware Material", ScanField.Ignore),
            new FileProperty("Solid Wood Construction", ScanField.Ignore),
            new FileProperty("Corner Block", ScanField.Ignore),
            new FileProperty("Custion or Upholstery Fill Material", ScanField.Ignore),
            new FileProperty("Foam Density", ScanField.Ignore),
            new FileProperty("Seating Comfort", ScanField.Ignore),
            new FileProperty("Removable Cushion", ScanField.Ignore),
            new FileProperty("Removable Upholstery Cover", ScanField.Ignore),
            new FileProperty("Upholstery Grade", ScanField.Ignore),
            new FileProperty("Welt On Cushions", ScanField.Ignore),
            new FileProperty("Skirted", ScanField.Ignore),
            new FileProperty("Casters", ScanField.Ignore),
            new FileProperty("Nested Stools", ScanField.Ignore),
            new FileProperty("Number of Nested Stools", ScanField.Ignore),
            new FileProperty("Nested Stool Storage", ScanField.Ignore),
            new FileProperty("Collapsible Nested Stools", ScanField.Ignore),
            new FileProperty("Collapsible", ScanField.Ignore),
            new FileProperty("Suitable As Seating", ScanField.Ignore),
            new FileProperty("Shelving", ScanField.Ignore),
            new FileProperty("Drawers", ScanField.Ignore),
            new FileProperty("Legs", ScanField.Ignore),
            new FileProperty("Storage", ScanField.Ignore),
            new FileProperty("Tools Needed", ScanField.Ignore),
            new FileProperty("Additional Parts Required", ScanField.Ignore),
            new FileProperty("Parts Needed", ScanField.Ignore),
            new FileProperty("Outdoor Safe?", ScanField.Ignore),
            new FileProperty("Product Care", ScanField.Ignore),
            new FileProperty("Product Warranty", ScanField.Ignore),
            new FileProperty("Assembly Required?", ScanField.Ignore),
            new FileProperty("Product Weight - Lbs", ScanField.Ignore),
            new FileProperty("Product Weight - G", ScanField.Ignore),
            new FileProperty("Weight Capacity - lbs", ScanField.Ignore),
            new FileProperty("Diameter", ScanField.Ignore),
            new FileProperty("Size - In", ScanField.Ignore),
            new FileProperty("Size - Cm", ScanField.Ignore),
            new FileProperty("Width - In", ScanField.Ignore),
            new FileProperty("Length - In", ScanField.Ignore),
            new FileProperty("Height - In", ScanField.Ignore),
            new FileProperty("Width - Cm", ScanField.Ignore),
            new FileProperty("Length - Cm", ScanField.Ignore),
            new FileProperty("Height - Cm", ScanField.Ignore),
            new FileProperty("Custom Size Available?", ScanField.Ignore),
            new FileProperty("Shelf Height - Top to Bottom - In", ScanField.Ignore),
            new FileProperty("Shelf Width - Side to Side - In", ScanField.Ignore),
            new FileProperty("Shelf Depth - Front to Back - In", ScanField.Ignore),
            new FileProperty("Drawer Interior Height - Top to Bottom - In", ScanField.Ignore),
            new FileProperty("Drawer Interior Width - Side to Side - In", ScanField.Ignore),
            new FileProperty("Drawer Interior Depth - Front to Back - In", ScanField.Ignore),
            new FileProperty("Leg Height - Top to Bottom - In", ScanField.Ignore),
            new FileProperty("Leg Width - Side to Side - In", ScanField.Ignore),
            new FileProperty("Leg Depth - Front to Back - In", ScanField.Ignore),
            new FileProperty("Storage Space Height - Top to Bottom - In", ScanField.Ignore),
            new FileProperty("Storage Space Width - Side to Side - In", ScanField.Ignore),
            new FileProperty("Storage Space Depth - Front to Back - In", ScanField.Ignore),
            new FileProperty("Main Image", ScanField.Ignore),
            new FileProperty("Additional Image 1", ScanField.Ignore),
            new FileProperty("Additional Image 2", ScanField.Ignore),
            new FileProperty("Additional Image 3", ScanField.Ignore),
            new FileProperty("Additional Image 4", ScanField.Ignore),
            new FileProperty("Additional Products Shown in Images", ScanField.Ignore),
            new FileProperty("Video Link", ScanField.Ignore),
            new FileProperty("Lead Time", ScanField.Ignore),
            new FileProperty("Ship Method", ScanField.Ignore),
            new FileProperty("NMFC Code", ScanField.Ignore),
            new FileProperty("Freight Class", ScanField.Ignore),
            new FileProperty("Carton Weight - Lbs", ScanField.Ignore),
            new FileProperty("Carton Weight - G", ScanField.Ignore),
            new FileProperty("Shipping Dimensions - In", ScanField.Ignore),
            new FileProperty("Shipping Dimensions - Cm", ScanField.Ignore),
            new FileProperty("Carton Height - In", ScanField.Ignore),
            new FileProperty("Carton Width - In", ScanField.Ignore),
            new FileProperty("Carton Depth - In", ScanField.Ignore),
            new FileProperty("Carton Height - Cm", ScanField.Ignore),
            new FileProperty("Carton Width - Cm", ScanField.Ignore),
            new FileProperty("Carton Depth - Cm", ScanField.Ignore),
            new FileProperty("Eco-Friendly", ScanField.Ignore),
            new FileProperty("ANSI/BIFMA Compliant", ScanField.Ignore),
            new FileProperty("GSA Approved", ScanField.Ignore),
            new FileProperty("CARB Compliant", ScanField.Ignore),
            new FileProperty("NFPA Compliant", ScanField.Ignore),
            new FileProperty("BHFTI Upholstered Furniture Flammability Compliant", ScanField.Ignore),
            new FileProperty("Contains Flame Retardant Materials", ScanField.Ignore),
            new FileProperty("Non-Toxic", ScanField.Ignore),
            new FileProperty("Fire Resistant", ScanField.Ignore),
            new FileProperty("Scratch Resistant", ScanField.Ignore),
            new FileProperty("Stain Resistant", ScanField.Ignore),
            new FileProperty("Water Resistant", ScanField.Ignore),
            new FileProperty("Water Resistant Details", ScanField.Ignore),
            new FileProperty("Recycled Content", ScanField.Ignore),
            new FileProperty("Total Recycled Content (Percentage)", ScanField.Ignore),
            new FileProperty("Post-Consumer Content (Percentage)", ScanField.Ignore),
            new FileProperty("Remanufactured/Refurbished", ScanField.Ignore),
            new FileProperty("FSC Certified", ScanField.Ignore),
            new FileProperty("ISTA 3A Certified", ScanField.Ignore),
            new FileProperty("Green Guard Certified", ScanField.Ignore),
            new FileProperty("TB117-2013 Compliant", ScanField.Ignore),
        };
        
        private readonly IStorageProvider<SuryaHomewareVendor> _storageProvider;
        public SuryaPoufFileLoader(IStorageProvider<SuryaHomewareVendor> storageProvider)
        {
            _storageProvider = storageProvider;
        }

        public List<ScanData> LoadProducts()
        {
            var staticFileFolder = _storageProvider.GetStaticFolder();
            var fileLoader = new ExcelFileLoader();
            var products = fileLoader.Load(Path.Combine(staticFileFolder, "SuryaPoufs.xlsx"), _properties, ScanField.ManufacturerPartNumber, 1, 2);
            products.ForEach(x => x[ScanField.Category5] = "poufs");
            return products.GroupBy(x => x[ScanField.Pattern]).Select(x => new ScanData(x.First()) {Variants = x.ToList()}).ToList();
        }
    }
}