using NUnit.Framework;
using ProductScanner.Core.Scanning.Products.FieldTypes;

namespace ProductScanner.Core.Tests
{
    [TestFixture]
    public class CountryTests
    {
        [TestCase("", null)]
        [TestCase("NONE", null)]
        [TestCase("No Country of Origin", null)]
        [TestCase("Usa", "USA")]
        [TestCase("United States U.S.A.", "USA")]
        [TestCase("U.S.A.", "USA")]
        [TestCase("U.S.A", "USA")]
        [TestCase("U..S.A.", "USA")]
        [TestCase("U.S.A..", "USA")]
        [TestCase("USE", "USA")]
        [TestCase("U.S.", "USA")]
        [TestCase("US", "USA")]
        [TestCase("Us", "USA")]
        [TestCase("US/CN", "USA")]
        [TestCase("United States", "USA")]
        [TestCase("Made in USA", "USA")]
        [TestCase("United States of America", "USA")]
        [TestCase("Printed In U.S.A.", "USA")]
        [TestCase("Dyed In U.S.A.", "USA")]
        [TestCase("Greige U.S.A.", "USA")]
        [TestCase("Taiwan Greige U.S.A.", "USA")]
        [TestCase("Greige Taiwan U.S.A.", "USA")]
        [TestCase("Pakistan Greige Usa", "USA")]
        [TestCase("Griege China U.S.A.", "USA")]
        [TestCase("Greige Pakistan Usa", "USA")]
        [TestCase("Greige Pakistanu.S.A", "USA")]
        [TestCase("Greige Printed U.S.A", "USA")]
        [TestCase("Finish In U.S.A.", "USA")]
        [TestCase("Greige Dyed U.S.A.", "USA")]
        [TestCase("China Greige U.S.A.", "USA")]
        [TestCase("Finished In U.S.A.", "USA")]
        [TestCase("Belarus U.S.A.", "USA")]
        [TestCase("K.S.A.", "Saudi Arabia")]
        [TestCase("CN", "China")]
        [TestCase("KOREA", "Korea")]
        [TestCase("Korea Import", "Korea")]
        [TestCase("BE", "Belgium")]
        [TestCase("MX", "Mexico")]
        [TestCase("EG", "Egypt")]
        [TestCase("U.K.", "United Kingdom")]
        [TestCase("UK", "United Kingdom")]
        [TestCase("Uk", "United Kingdom")]
        [TestCase("U.K. Kingdom", "United Kingdom")]
        [TestCase("United Kingdom", "United Kingdom")]
        [TestCase("United Kingd", "United Kingdom")]
        [TestCase("United Kngdm", "United Kingdom")]
        [TestCase("United Kinddom", "United Kingdom")]
        [TestCase("Printed United Kingdom", "United Kingdom")]
        [TestCase("Printed U.K. Kingdom", "United Kingdom")]
        [TestCase("Printedunitedkingdom", "United Kingdom")]
        [TestCase("Brasil", "Brazil")]
        [TestCase("Inda", "India")]
        [TestCase("IN", "India")]
        [TestCase("india", "India")]
        [TestCase("Spain & Canary Islands", "Spain and Canary Islands")]
        [TestCase("Turkmenista", "Turkmenistan")]
        [TestCase("Turkeminista", "Turkmenistan")]
        [TestCase("Turkeministan", "Turkmenistan")]
        [TestCase("United Arab", "United Arab Emirates")]
        [TestCase("Uae", "United Arab Emirates")]
        [TestCase("United Arab Emi", "United Arab Emirates")]
        [TestCase("S.Korea", "South Korea")]
        [TestCase("S. Korea", "South Korea")]
        [TestCase("Philippinnes", "Philippines")]
        [TestCase("France Import", "France")]
        [TestCase("FR", "France")]
        [TestCase("Holland Import", "Holland")]
        [TestCase("Unknown", null)]
        [TestCase("?", null)]
        [TestCase("Nice", null)]
        [TestCase("To Be Determined At Lot Level", null)]
        [TestCase("Belguim", "Belgium")]
        public void TestFormat(string input, string output)
        {
            var country = new Country(input);
            Assert.AreEqual(output, country.Format());
        }
    }
}