using System.Collections.Generic;
using System.IO;
using ProductScanner.Core.Scanning.FileLoading;
using ProductScanner.Core.Scanning.Products.Vendor;
using ProductScanner.Core.Scanning.Storage;

namespace WildWoodLamps
{
    public class WildWoodLampsFileLoader
    {
        private static readonly List<FileProperty> Properties = new List<FileProperty>
        {
            new FileProperty("BaseItemCode", ScanField.ManufacturerPartNumber),
            new FileProperty("Name", ScanField.ProductName),
            new FileProperty("Materials", ScanField.Material),
            new FileProperty("Finish", ScanField.Finish),
            new FileProperty("ShortDesc", ScanField.Description),
            new FileProperty("LongDesc", ScanField.LongDescription),
            new FileProperty("KeyWords", ScanField.Keywords),
            new FileProperty("ImageFileName", ScanField.ImageUrl),
            new FileProperty("Dimensions", ScanField.Dimensions),
            new FileProperty("ShipWeight", ScanField.ShippingWeight),
            new FileProperty("PackedVolume", ScanField.Ignore),
            // always 1
            new FileProperty("PackQuantity", ScanField.Ignore),
            new FileProperty("MinimumQuantity", ScanField.Ignore),

            new FileProperty("TradeNameCode", ScanField.Brand),
            new FileProperty("CollectionCode", ScanField.Collection),
            new FileProperty("CategoryCode", ScanField.CategoryCode),
            new FileProperty("CountryOfOrigin", ScanField.Country),
            new FileProperty("MaterialDescription", ScanField.Ignore),
            new FileProperty("NewItem", ScanField.Ignore),
            new FileProperty("WholesalePrice", ScanField.Cost),
            new FileProperty("SuggestedRetail", ScanField.RetailPrice),
            new FileProperty("FinishCode", ScanField.Ignore),
            new FileProperty("FinishName", ScanField.Ignore),
            new FileProperty("CatalogPage", ScanField.Ignore),
            new FileProperty("ShadeNumber", ScanField.Ignore),
            new FileProperty("ShadeColor", ScanField.Color),
            new FileProperty("ShadeFabric", ScanField.ShadeMaterial),
            new FileProperty("CartonHeight", ScanField.Ignore),
            new FileProperty("CartonWidth", ScanField.Ignore),
            new FileProperty("CartonDepth", ScanField.Ignore),
            new FileProperty("CartonCBM", ScanField.Ignore),
            new FileProperty("ActualWeight", ScanField.Ignore),
            new FileProperty("DimWeight", ScanField.Ignore),
            new FileProperty("ShadeCartonHeight", ScanField.Ignore),
            new FileProperty("ShadeCartonWidth", ScanField.Ignore),
            new FileProperty("ShadeCartonDepth", ScanField.Ignore),
            new FileProperty("ShadeCartonCBM", ScanField.Ignore),
            new FileProperty("ShadeActualWeight", ScanField.Ignore),
            new FileProperty("ShadeDimWidth", ScanField.Ignore),
            new FileProperty("SwitchType", ScanField.SwitchType),
            new FileProperty("MaxWattage", ScanField.Wattage),
            new FileProperty("BulbCode", ScanField.Bulb),
            new FileProperty("BulbCount", ScanField.Bulbs),
            new FileProperty("Width", ScanField.Width),
            new FileProperty("Depth", ScanField.Depth),
            new FileProperty("Height", ScanField.Height),
            new FileProperty("ArmHeight", ScanField.Ignore),
            new FileProperty("SeatHeight", ScanField.Ignore),
            new FileProperty("Diameter", ScanField.Diameter),
            new FileProperty("AccentWidth", ScanField.Ignore),
            new FileProperty("AccentDepth", ScanField.Ignore),
            new FileProperty("AccentDims", ScanField.Ignore),
            new FileProperty("ShadeDims", ScanField.Ignore),
            new FileProperty("UnitMeasure", ScanField.UnitOfMeasure),
            new FileProperty("PrevMarket", ScanField.Ignore),

            // what is up with all of these fields
            new FileProperty("Carton1_Height", ScanField.Ignore),
            new FileProperty("Carton1_Width", ScanField.Ignore),
            new FileProperty("Carton1_Depth", ScanField.Ignore),
            new FileProperty("Carton1_GWeight", ScanField.Ignore),
            new FileProperty("Carton1_NWeight", ScanField.Ignore),
            new FileProperty("Carton2_Height", ScanField.Ignore),
            new FileProperty("Carton2_Width", ScanField.Ignore),
            new FileProperty("Carton2_Depth", ScanField.Ignore),
            new FileProperty("Carton2_GWeight", ScanField.Ignore),
            new FileProperty("Carton2_NWeight", ScanField.Ignore),
            new FileProperty("Carton3_Height", ScanField.Ignore),
            new FileProperty("Carton3_Width", ScanField.Ignore),
            new FileProperty("Carton3_Depth", ScanField.Ignore),
            new FileProperty("Carton3_GWeight", ScanField.Ignore),
            new FileProperty("Carton3_NWeight", ScanField.Ignore),
            new FileProperty("Carton4_Height", ScanField.Ignore),
            new FileProperty("Carton4_Width", ScanField.Ignore),
            new FileProperty("Carton4_Depth", ScanField.Ignore),
            new FileProperty("Carton4_GWeight", ScanField.Ignore),
            new FileProperty("Carton4_NWeight", ScanField.Ignore),
            new FileProperty("Carton5_Height", ScanField.Ignore),
            new FileProperty("Carton5_Width", ScanField.Ignore),
            new FileProperty("Carton5_Depth", ScanField.Ignore),
            new FileProperty("Carton5_GWeight", ScanField.Ignore),
            new FileProperty("Carton5_NWeight", ScanField.Ignore),
            new FileProperty("Carton6_Height", ScanField.Ignore),
            new FileProperty("Carton6_Width", ScanField.Ignore),
            new FileProperty("Carton6_Depth", ScanField.Ignore),
            new FileProperty("Carton6_GWeight", ScanField.Ignore),
            new FileProperty("Carton6_NWeight", ScanField.Ignore),
            new FileProperty("Carton7_Height", ScanField.Ignore),
            new FileProperty("Carton7_Width", ScanField.Ignore),
            new FileProperty("Carton7_Depth", ScanField.Ignore),
            new FileProperty("Carton7_GWeight", ScanField.Ignore),
            new FileProperty("Carton7_NWeight", ScanField.Ignore),
            new FileProperty("Carton8_Height", ScanField.Ignore),
            new FileProperty("Carton8_Width", ScanField.Ignore),
            new FileProperty("Carton8_Depth", ScanField.Ignore),
            new FileProperty("Carton8_GWeight", ScanField.Ignore),
            new FileProperty("Carton8_NWeight", ScanField.Ignore),
            new FileProperty("Carton9_Height", ScanField.Ignore),
            new FileProperty("Carton9_Width", ScanField.Ignore),
            new FileProperty("Carton9_Depth", ScanField.Ignore),
            new FileProperty("Carton9_GWeight", ScanField.Ignore),
            new FileProperty("Carton9_NWeight", ScanField.Ignore),
            new FileProperty("Carton10_Height", ScanField.Ignore),
            new FileProperty("Carton10_Width", ScanField.Ignore),
            new FileProperty("Carton10_Depth", ScanField.Ignore),
            new FileProperty("Carton10_GWeight", ScanField.Ignore),
            new FileProperty("Carton10_NWeight", ScanField.Ignore),
            new FileProperty("Carton11_Height", ScanField.Ignore),
            new FileProperty("Carton11_Width", ScanField.Ignore),
            new FileProperty("Carton11_Depth", ScanField.Ignore),
            new FileProperty("Carton11_GWeight", ScanField.Ignore),
            new FileProperty("Carton11_NWeight", ScanField.Ignore),
            new FileProperty("Carton12_Height", ScanField.Ignore),
            new FileProperty("Carton12_Width", ScanField.Ignore),
            new FileProperty("Carton12_Depth", ScanField.Ignore),
            new FileProperty("Carton12_GWeight", ScanField.Ignore),
            new FileProperty("Carton12_NWeight", ScanField.Ignore),
            new FileProperty("Carton13_Height", ScanField.Ignore),
            new FileProperty("Carton13_Width", ScanField.Ignore),
            new FileProperty("Carton13_Depth", ScanField.Ignore),
            new FileProperty("Carton13_GWeight", ScanField.Ignore),
            new FileProperty("Carton13_NWeight", ScanField.Ignore),
            new FileProperty("Carton14_Height", ScanField.Ignore),
            new FileProperty("Carton14_Width", ScanField.Ignore),
            new FileProperty("Carton14_Depth", ScanField.Ignore),
            new FileProperty("Carton14_GWeight", ScanField.Ignore),
            new FileProperty("Carton14_NWeight", ScanField.Ignore),
            new FileProperty("Carton15_Height", ScanField.Ignore),
            new FileProperty("Carton15_Width", ScanField.Ignore),
            new FileProperty("Carton15_Depth", ScanField.Ignore),
            new FileProperty("Carton15_GWeight", ScanField.Ignore),
            new FileProperty("Carton15_NWeight", ScanField.Ignore),
        };

        private readonly IStorageProvider<WildWoodLampsVendor> _storageProvider;
        public WildWoodLampsFileLoader(IStorageProvider<WildWoodLampsVendor> storageProvider) { _storageProvider = storageProvider; }

        public List<ScanData> LoadInventoryData()
        {
            var staticFileFolder = _storageProvider.GetStaticFolder();
            var fileLoader = new ExcelFileLoader();
            return fileLoader.Load(Path.Combine(staticFileFolder, "products - all - 18052018.xlsx"), Properties, ScanField.ManufacturerPartNumber, 1, 2);
        }
    }
}